### ISSUE TITLE
use FALLOC_FL_ZERO_RANGE for write_zeroes

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vmm-sys-util#109]
While working on the virtio block discard/write_zeroes implementation, I noticed that `write_zeroes()` is using `fallocate` with FALLOC_FL_PUNCH_HOLE mode instead of FALLOC_FL_ZERO_RANGE. From [the virtio specification
](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html#x1-2500006) it makes sense to use FALLOC_FL_PUNCH_HOLE for write zeroes request only if `unmap` bit is also set, otherwise the zeroed region shouldn't be deallocated.

I think it would make sense to either update `write_zeroes()` with FALLOC_FL_ZERO_RANGE or add an extra parameter to that function (`mode` for example) which can be any `FallocateMode` variant.

Moreover, we can completely switch to [the latest crosvm `write_zeroes`](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/refs/heads/master/sys_util/src/write_zeroes.rs) which is using FALLOC_FL_ZERO_RANGE for `File` and adds a new trait `WriteZeroesAt` which lets you give the offset in file instead of using the current cursor. It also allows doing custom implementations for write_zeroes() (which might be useful for example for qcow file wrappers, example [here](https://chromium.googlesource.com/chromiumos/platform/crosvm/+/refs/heads/master/disk/src/qcow/mod.rs#1714)).

Any thoughts / suggestions?

**Comment by jiangliu** [comment]
The latest implementation from crosvm is preferred. Then the virtio-blk driver chooses to call punch_hole() or write_zeroes_at() according to the `unmap` flag for VIRTIO_BLK_T_WRITE_ZEROES requests.

**Comment by lauralt** [comment]
That's how I was seeing it too, thanks! I'll open a PR with the switch.
