### ISSUE TITLE
crates.io publishing

### ISSUE THREAD

**Issue by sameo** [rust-vmm/vmm-sys-util#11]
Missing requirements for publishing to crates.io:
- [x] Add `#![deny(missing_docs)]` to `src/lib.rs`
- [x] In crate documentation. To check the documentation in HTML version run `cargo doc --open`
- [x] Format the documentation with common sections like `#Examples`, `#Arguments` and `Errors` where applicable
- [x] Update README.md
- [x] Switch to rust-vmm-ci #9 
- [x] Check coverage of project and add more unit tests (if needed).
- [x] Add CODEOWNERS
- [x] Update crate metadata #13

**Comment by andreeaflorescu** [comment]
Current Coverage: 67.9%
The coverage is easy to improve because we are not testing some basic functionality that doens't look very difficult to test. Added the following issues to track this: #24 #25 #26

**Comment by andreeaflorescu** [comment]
Crate published to crates.io: https://crates.io/crates/vmm-sys-util
