### ISSUE TITLE
Syslog tests intermittent failures

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-sys-util#21]
The failures happen because all tests in one crate are running in a single process. This means we call `init()` multiple time in the same process which is results in undefined behaviour.

Fixing this is as easy as having just one unit test for the syslog module.

**Comment by jiangliu** [comment]
I encountered several random failures with the syslog mod too, thanks for root-causing.

**Comment by andreeaflorescu** [comment]
I am working on a fix. But this is gonna be a dummy one. Most tests in syslog are actually "coverage" test in the sense that they just call functions and not actually check that the function did what it is expected to do. I'll add a separate issue to fix the tests and check the results.
