### ISSUE TITLE
timerfd.rs - add unit tests

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-sys-util#25]
The coverage as of 30 July 2019 is 67.9%.

The following functions and trait implementations are not tested:
- `clear()`
- `FromRawFd`
- `IntoRawFd`

Also, error cases are also not tested, but I am not sure how feasible it is to test them.

**Comment by liujing2** [comment]
@andreeaflorescu  With #30, the coverage increases to 94.1%. Error cannot easily test..
