### ISSUE TITLE
poll.rs - add unit tests

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-sys-util#26]
The following things need to be tested:
- `Default` implementation for `EpollEvents`
- `PollToken` implementation for u8, u16, u64.

Also the error cases are not tested, we should check if it is feasible to test the error cases as well.

**Comment by andreeaflorescu** [comment]
We should put this on hold for a bit. Right now the Firecracker team is re-working the wrappers over `epoll` and we would like to contribute this back to rust-vmm.

**Comment by aghecenco** [comment]
Covered in `event-manager`. Closing.
