### ISSUE TITLE
No proper documentation for some definitions in ioctl.rs 

### ISSUE THREAD

**Issue by liujing2** [rust-vmm/vmm-sys-util#33]
@sameo @andreeaflorescu @jiangliu 
There are many const variables copied from linux kernel that don't have a proper documentation.
Does anyone have some suggestion?

https://github.com/rust-vmm/vmm-sys-util/blob/7222869ed3de260bb147781c4334d6f89f55eb0a/src/ioctl.rs#L171

**Comment by jiangliu** [comment]
I don't think it adds too much values to document these consts:)

**Comment by andreeaflorescu** [comment]
Closing this as I don't believe we need to document those consts. We should do add allow missing docs for them, but it seems unrelated to this issue.
