### ISSUE TITLE
Block other signals while a registered signal handler is running

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/vmm-sys-util#52]
Just noticed that `register_signal_handler` from `signal.rs`: https://github.com/rust-vmm/vmm-sys-util/blob/472614c3a21231f6a0c3696fab83fb34d6592ade/src/signal.rs#L191, lacks a way to specify to a signal handler what signals to be blocked while it is running.

To be specific, I am referring to a way to initialize the `sa_mask` field of a `struct sigaction`, when calling `register_signal_handler`. An example of my usecase is here [0].

Are you fond of a way to achieve this with the current implementation?
If it couldn't be achieved with the current implementation, I can gladly contribute with a PR.

[0] https://www.gnu.org/software/libc/manual/html_node/Blocking-for-Handler.html#Blocking-for-Handler.

**Comment by andreeaflorescu** [comment]
To give a bit more context, we are currently working on consuming vmm-sys-util in Firecracker and we need this functionality to consume the signal module as well.
