### ISSUE TITLE
the trait `std::error::Error` is not implemented for `vmm_sys_util::errno::Error`

### ISSUE THREAD

**Issue by haraldh** [rust-vmm/vmm-sys-util#58]
SSIA :smile:

**Comment by MrXinWang** [comment]
Trying to work on this :)

If I understand this subject correctly (Please do correct me if I am wrong :P), we only need to implement [`fn source(&self) -> Option<&(dyn Error + 'static)>`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source) as there is an existing implementation of [`Display`](https://github.com/rust-vmm/vmm-sys-util/blob/664bb8df997b29c00edc8b32a90639e6158b68f6/src/errno.rs#L100) and [`fn backtrace(&self) -> Option<&Backtrace>`](https://doc.rust-lang.org/std/error/trait.Error.html#method.backtrace) is a nightly feature.
