### ISSUE TITLE
Export as public SIGRTMIN() and SIGRTMAX()

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/vmm-sys-util#62]
The methods which are used for getting base signum for real-time signals, namely `SIGRTMIN()` and `SIGRTMAX()`, from `signal.rs`, are private. It would be nice to expose them as public, with the advent of manually passing real-time signums to methods which register and validate signal handlers, like `register_signal_handler` and `validate_signal_num`, from `signal.rs`.

**Comment by andreeaflorescu** [comment]
This was already fixed in https://github.com/rust-vmm/vmm-sys-util/pull/59
