### ISSUE TITLE
TempFile and TempDir support for file operations

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/vmm-sys-util#64]
Two options worth considering:

1. Add support for temporary file operations, like read, write, seek, but also support for file permissions (open TempFile with specific file permissions). Some progress was done in this direction: https://github.com/rust-vmm/vmm-sys-util/pull/60.

2. When creating a temporary file/directory, we should unlink it immediately, then return a File that represent the handle for that unliked file/directory, that we're gonna operate with, and leave altogether the TempFile/TempDir structs as builders for these temporary files. This would simplify a lot the implementation, and wouldn't need any support for file operations and permissions.

**Comment by acatangiu** [comment]
I don't agree with option 2. There are cases where one is interested in using the temp file path, unlinking the file on creation makes us lose the the property of "having temporary file `F` at the temporary path `P`".

Let's look at the multiple possible use-cases and make the right decision. We might find that solving all use-cases using a single object type is not possible.

From a bird's eye view option 1 should satisfy all requirements, **if** we implement all relevant `io` traits for the `TempFile` wrapper. On top of those, `TempFile` should also offer a `fn into_file(self) -> File` method that provides the owned `File` (the method consumes `self` so it also unlinks the file).

**Comment by aghecenco** [comment]
What's the problem we want to solve?
* there are use cases where we need `File` operations
* there are use cases when we just need a random tmp path

I would leave `TempFile` stripped bare of functionality and immediately unlinking but exposing both an
* `into_file` which returns a `File` that we can operate on normally
* `into_path` which returns a `str` that we can use to manually control the file's lifecycle

both consuming the `TempFile`.

WDYT?

**Comment by acatangiu** [comment]
I would like to give the user some control on when the file is unlinked from the file system. That’s why I don’t like any of the options that immediately unlink.

Let’s say for example you want to use a TempFile and have a reader and a writer in your code both of which requiring owning the file. With normal files you can achieve this by simply opening the same file twice each open giving you an owned File object. If we immediately unlink the TempFile, we lose this expected file behaviour.

The more I think about it, the more I support the idea that TempFile should be an “invisible” wrapper over File (meaning it should implement io traits). TempFile specific behaviour is creating the file in TEMPDIR and unlinking the file on Drop.

**Comment by alexandruag** [comment]
I think it's worth looking into implementing `Deref` and `DerefMut` with `Target=File` for `TempFile`, so the automatic coercion allows users to call `File` methods on a `TempFile` object without proxy-ing them individually in many contexts. Also, looks like adding a method along the lines of `into_owned(self) -> File` would be useful.
