### ISSUE TITLE
Replace `errno::Error` with `io::Error`?

### ISSUE THREAD

**Issue by exrook** [rust-vmm/vmm-sys-util#76]
Is there a reason `errno::Error` is used instead of `std::io::Error`?

I've created a [branch](https://github.com/rust-vmm/vmm-sys-util/compare/master...exrook:err_no_more) replacing `errno::Error` with `io::Error`. The main changes were: 
replacing `errno::Error::new()` with `io::Error::from_raw_os_error()` and
replacing `errno::Error::last()` with `errno::Error::last_os_error()`

The only major change is that `io::Error` does not implement `PartialEq` so either `ErrorKind` or `raw_os_error()` needs to be used to compare errors.

This is a breaking change for consumers of this crate, but `io::Error` provides all the same functionality with different method names, so upgrading should be straightforward.

**Comment by andreeaflorescu** [comment]
We were previously using io::Error and we switched to errno instead. It was annoying that io::Error does not implement PartialEq, we use it quite a lot to test that the errors returned from a functions are the expected ones.

**Comment by connorkuehl** [comment]
@exrook Starting from v0.6.1 (80abb6f6264e254fb627d211f62f179ce4299c10), client code should be able to convert between `io::Error` and `errno::Error` seamlessly. Does this help your use case?

**Comment by andreeaflorescu** [comment]
@exrook I'll be closing this, please re-open if it is still needed.
