### ISSUE TITLE
Add struct_util module from linux-loader

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/vmm-sys-util#77]
See also https://github.com/rust-vmm/linux-loader/issues/20, https://github.com/rust-vmm/linux-loader/pull/23#discussion_r390287530

[`struct_util`](https://github.com/rust-vmm/linux-loader/blob/master/src/loader/struct_util.rs) is a generic utility module that reads structs from bytes. It should be included in this utility crate and consumed by `linux-loader` from here.

**Comment by bonzini** [comment]
There is some overlap between this and vm-memory's Bytes and ByteValued traits. Can you try instead implementing ByteValued on the structs and using the read_obj/write_obj methods from the Bytes trait? The main limitation is that you need a *mutable* reference to slice but it shouldn't be a problem for linux-loader.

**Comment by aghecenco** [comment]
Indeed we can `impl ByteValued` on the headers currently read with `struct_util`, and that gets us elegantly rid of `struct_util`; later on, the `GuestMemory` reads the whole kernel image, not just the header, as a generic `F: Read` (for elf format: [link](https://github.com/rust-vmm/linux-loader/blob/0c754f380acaa905e764a6a41175275cbc7d761b/src/loader/mod.rs#L266)).

We'd be replacing
```rust
let mut ehdr: elf::Elf64_Ehdr = Default::default();
unsafe { struct_util::read_struct(kernel_image, &mut ehdr).map_err(|_| Error::ReadElfHeader)?; }
```
with
```rust
let mut ehdr_bytes = vec![0u8; mem::size_of::<elf::Elf64_Ehdr>()];
kernel_image.read_exact(ehdr_bytes.as_mut_slice()).map_err(|_| Error::ReadElfHeader)?;
let ehdr = elf::Elf64_Ehdr::from_mut_slice(ehdr_bytes.as_mut_slice()).ok_or(Error::ReadElfHeader)?;
```
which I don't necessarily find more elegant, but personally prefer to moving `struct_util` around and making it `pub`.
It might be more elegant if `kernel_image` were a `Bytes` and not just a `Read + Seek`, so we could `read_obj` from it directly, but I think that would be too restrictive on `linux-loader`.

**Comment by bonzini** [comment]
Yes, it's not super nice but at least it doesn't have unsafe. You can also put `ehdr_bytes.as_mut_slice()` into a local variable which is a bit nicer. Or perhaps use an array like

```rust
let mut ehdr_bytes = [0u8; mem::size_of::<elf::Elf64_Ehdr>()];
kernel_image.read_exact(&mut ehdr_bytes[..]).map_err(|_| Error::ReadElfHeader)?;
let ehdr = elf::Elf64_Ehdr::from_mut_slice(&mut ehdr_bytes[..]).ok_or(Error::ReadElfHeader)?;
```

?

**Comment by bonzini** [comment]
Also:

```rust
let mut ehdr_bytes = [0u8; mem::size_of::<elf::Elf64_Ehdr>()];
ehdr_bytes.as_volatile_slice().read_from(0, kernel_image, ehdr_bytes.len()).map_err(|_| Error::ReadElfHeader)?;
let ehdr = elf::Elf64_Ehdr::from_mut_slice(&mut ehdr_bytes[..]).ok_or(Error::ReadElfHeader)?;
```

... and finally, we could implement `VolatileMemory` on ByteValued (rust-vmm/vm-memory#and do

```rust
let mut ehdr: elf::Elf64_Ehdr = Default::default();
ehdr.as_volatile_slice().read_from(0, kernel_image, ehdr.len()).map_err(|_| Error::ReadElfHeader)?;
```

**Comment by aghecenco** [comment]
The last solution looks great and I find it to be the most elegant alternative to `struct_util`. Until https://github.com/rust-vmm/vm-memory/pull/83 is merged & released, I'll go ahead with the other solution.
