### ISSUE TITLE
FamStructWrapper: incorrect Clone implementation 

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vmm-sys-util#85]
`Clone` implementation for `FamStructWrapper` keeps only the number of entries and the entries array members. This implementation should be either removed or modified so that all fields are cloned.

**Comment by Twister915** [comment]
I'm trying to understand this issue, please correct me if I'm wrong. A FAM struct, in the typical case, just has length and a bunch of entries. Therefore, in this case, the `Clone` implementation is correct. However, FAM doesn't strictly need length + elements, but can have ... other fields ... + length + ... other fields ... + entries, and this is the case that `Clone` does not currently handle correctly. If that's correct, then I think if #104 is addressed first, then this should be pretty straight-forward.

**Comment by andreeaflorescu** [comment]
@Twister915 I find it to be the other way around. We already support other fields in FAM Struct, but the clone is implemented such that only the `entries` and `length` are cloned. This makes the `Clone` implementation wrong, and as a consequence, the `FamStructWrapper` implementation also wrong (in the scenarios where clone is needed). Once we fix the clone, and add a few tests with FAM structs that have more fields, we can close both issues.
