### ISSUE TITLE
Request for new crates.io release

### ISSUE THREAD

**Issue by connorkuehl** [rust-vmm/vmm-sys-util#90]
I understand if you'd rather wait to fit in other changes, but there is an unreleased change on the master branch I'd like to use downstream. It wouldn't be the most exciting release :sweat_smile: but I'd appreciate it if/when it does happen. :slightly_smiling_face:

**Comment by andreeaflorescu** [comment]
I don't think we have anything in the pipeline right now. We can do a patch release since no breaking changes were added by that commit. I'll can do that now. If there are any other changes we can do another publish.

**Comment by andreeaflorescu** [comment]
https://crates.io/crates/vmm-sys-util/0.6.1
